app = 'user-recommendation-miniapp'
primary_region = 'fra'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1GB'
cpu_kind = 'shared'
cpus = 1
