# fly.toml app configuration file generated for mbd-miniapp-feedshowcase on 2025-06-26T17:41:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mbd-miniapp-feedshowcase'
primary_region = 'fra'

[build]

[env]
  PORT = '3000'

[processes]
  app = 'bun --cwd packages/server src/index.ts'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
