# fly.toml app configuration file generated for zerion-miniapp-portfolio on 2025-07-26T02:37:12+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'minikit-nextjs-miniappfeed'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1GB'
  cpu_kind = 'shared'
  cpus = 1
