/** 
 * Auto-generated by effect-start.
 */

import type { Router } from "effect-start"

const layout__ = {
  path: "/",
  load: () => import("./_layout.tsx"),
} as const

const page__ = {
  path: "/",
  parent: layout__,
  load: () => import("./_page.tsx"),
} as const

const server__api__debug = {
  path: "/api/debug",
  load: () => import("./api/debug/_server.ts"),
} as const

const server__api__farcaster = {
  path: "/api/farcaster",
  load: () => import("./api/farcaster/_server.ts"),
} as const

const server__api__labels = {
  path: "/api/labels",
  load: () => import("./api/labels/_server.ts"),
} as const

const server__api__users = {
  path: "/api/users",
  load: () => import("./api/users/_server.ts"),
} as const

export const Layouts: Router.LayoutRoutes = [
  layout__
] as const

export const Pages: Router.PageRoutes = [
  page__
] as const

export const Servers: Router.ServerRoutes = [
  server__api__debug,
  server__api__farcaster,
  server__api__labels,
  server__api__users
] as const
 