name: SDK Integration Test Suite

on:
  push:
    branches: [ master ]
    paths:
      - 'packages/sdk/**'
      - 'packages/types/**'
      - '.github/workflows/test-sdk.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'packages/sdk/**'
      - 'packages/types/**'
      - '.github/workflows/test-sdk.yml'
  workflow_dispatch: # Allow manual trigger

jobs:
  test-sdk:
    name: Test SDK
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build types package
        run: bun run build:types

      - name: Build SDK package  
        run: bun run build:sdk

      - name: Run SDK test suite
        run: |
          cd packages/sdk
          bun run test:integration
        env:
          API_KEY_EMBED: ${{ secrets.API_KEY_EMBED }}

      - name: Generate coverage report
        run: |
          cd packages/sdk
          bun run coverage
        env:
          API_KEY_EMBED: ${{ secrets.API_KEY_EMBED }}
        continue-on-error: true

      - name: Test individual namespaces
        run: |
          cd packages/sdk
          echo "🔍 Testing search.posts namespace..."
          bun run test:posts
          
          echo "👥 Testing search.users namespace..."
          bun run test:users
          
          echo "📰 Testing feed namespace..."
          bun run test:feed
        env:
          API_KEY_EMBED: ${{ secrets.API_KEY_EMBED }}

  test-sdk-without-key:
    name: Test SDK (No API Key)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build types package
        run: bun run build:types

      - name: Build SDK package
        run: bun run build:sdk

      - name: Test SDK without API key (should skip gracefully)
        run: |
          cd packages/sdk
          echo "🧪 Testing without API key - tests should skip gracefully"
          bun run test --reporter=verbose | grep -E "(skip|SKIP)" || echo "✅ Tests handled missing API key correctly"
        # No API_KEY_EMBED set - tests should skip gracefully

  test-typescript-compilation:
    name: TypeScript Compilation
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check TypeScript compilation
        run: |
          cd packages/sdk
          bun run check
          echo "✅ All test files compile successfully" 
